#! /usr/bin/env python3
"""Manage Arch Linux packages and repositories."""

from argparse import ArgumentParser
from configparser import ConfigParser
from pathllib import Path
from repotool import Repository


DESCRIPTION = 'Manage Arch Linux packages and repositories.'


def get_args():
    """Parses and returns the command line arguments."""

    parser = ArgumentParser(description=DESCRIPTION)
    parser.add_argument('repository', help='the target repository')
    parser.add_argument(
        'package', type=Path, nargs='+',
        help='the packages to add to the respository')
    parser.add_argument(
        '-s', '--sign', action='store_true',
        help='sign the packages and repository')
    parser.add_argument(
        '-r', '--rsync', action='store_true',
        help='rsync the repository to the configured location')
    parser.add_argument('-t', '--target', help='the rsync target')
    parser.add_argument('-d', '--delete', help='invoke rsync with delete flag')
    return parser.parse_args()


def main():
    """Main program."""

    args = get_args()
    config = ConfigParser()
    config.read('/etc/repotool.conf')
    repository = Repository.from_config(config[args.repository])

    for package in args.package:
        repository.add(package, sign=args.sign)

    if args.sync:
        repository.rsync(target=args.target, delete=args.delete)


if __name__ == '__main__':
    main()
